create table if not exists public.agendamentos (
    id bigint generated by default as identity primary key,
    nome text not null,
    whatsapp text not null,
    servico text not null,
    preco text,
    data date not null,
    horario time not null,
    criado_em timestamptz not null default now(),
    unique (data, horario)
);

create table if not exists public.dias_disponiveis (
    dia_semana smallint primary key check (dia_semana between 0 and 6),
    ativo boolean not null default true
);

create table if not exists public.horarios_disponiveis (
    horario time primary key,
    ativo boolean not null default true
);

insert into public.dias_disponiveis (dia_semana, ativo)
values
    (0, false),
    (1, true),
    (2, true),
    (3, true),
    (4, true),
    (5, true),
    (6, true)
on conflict (dia_semana) do nothing;

insert into public.horarios_disponiveis (horario, ativo)
values
    ('09:00', true),
    ('09:30', true),
    ('10:00', true),
    ('10:30', true),
    ('11:00', true),
    ('11:30', true),
    ('13:00', true),
    ('13:30', true),
    ('14:00', true),
    ('14:30', true),
    ('15:00', true),
    ('15:30', true),
    ('16:00', true),
    ('16:30', true),
    ('17:00', true),
    ('17:30', true),
    ('18:00', true),
    ('18:30', true),
    ('19:00', true)
on conflict (horario) do nothing;

alter table public.agendamentos enable row level security;
alter table public.dias_disponiveis enable row level security;
alter table public.horarios_disponiveis enable row level security;

drop policy if exists "Permitir leitura publica de agendamentos" on public.agendamentos;
drop policy if exists "Permitir criar agendamentos" on public.agendamentos;
drop policy if exists "Permitir atualizar agendamentos" on public.agendamentos;
drop policy if exists "Permitir excluir agendamentos" on public.agendamentos;

create policy "Permitir leitura publica de agendamentos"
on public.agendamentos for select
to anon
using (true);

create policy "Permitir criar agendamentos"
on public.agendamentos for insert
to anon
with check (true);

create policy "Permitir atualizar agendamentos"
on public.agendamentos for update
to anon
using (true)
with check (true);

create policy "Permitir excluir agendamentos"
on public.agendamentos for delete
to anon
using (true);

drop policy if exists "Permitir leitura publica de dias" on public.dias_disponiveis;
drop policy if exists "Permitir alterar dias" on public.dias_disponiveis;

create policy "Permitir leitura publica de dias"
on public.dias_disponiveis for select
to anon
using (true);

create policy "Permitir alterar dias"
on public.dias_disponiveis for all
to anon
using (true)
with check (true);

drop policy if exists "Permitir leitura publica de horarios" on public.horarios_disponiveis;
drop policy if exists "Permitir alterar horarios" on public.horarios_disponiveis;

create policy "Permitir leitura publica de horarios"
on public.horarios_disponiveis for select
to anon
using (true);

create policy "Permitir alterar horarios"
on public.horarios_disponiveis for all
to anon
using (true)
with check (true);
